<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e0df2db5-7eb9-4dc0-a218-b6077d0e9907</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <EnableNETAnalyzers>true</EnableNETAnalyzers>
	  <!-- Treat all warnings as errors -->
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="9.1.0-preview.1.25064.3" />
    <!--<PackageReference Include="Microsoft.Identity.Web" Version="3.7.1" />-->
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="3.7.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotNet9.Application\DotNet9.Application.csproj" />
    <ProjectReference Include="..\DotNet9.Insfrastructure\DotNet9.Insfrastructure.csproj" />
  </ItemGroup>

</Project>
